version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: my-postgres
    environment:
      POSTGRES_USER: accounts_user
      POSTGRES_PASSWORD: secret_pass
      POSTGRES_DB: accounts_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U accounts_user"]
      interval: 10s
      retries: 5

volumes:
  pgdata:
